builds:
  - binary: go-dork
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
  
archives:
  - id: binary
    format: binary